apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: nri-bundle
    repo: https://helm-charts.newrelic.com
    version: 5.0.25
    releaseName: nri-bundle
    namespace: newrelic
    valuesFile: values.yaml
#patches:
#  - target:
#      kind: ServiceAccount
#    path: remove-helm-annotations.patch.yaml
#  - target:
#      kind: ClusterRole
#    path: remove-helm-annotations.patch.yaml

patches:
  - target:
      kind: Certificate
      name: nri-bundle-nri-metadata-injection-webhook-cert
    path: 8760h0m0s-duration.patch.yaml
  - target:
      kind: Certificate
      name: nri-bundle-nri-metadata-injection-root-cert
    path: 43800h0m0s-duration.patch.yaml
