name: CI

on:
  pull_request: {}
  push: {}
  workflow_dispatch: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: imranismail/setup-kustomize@v2
      - uses: actions/checkout@v4
      - run: ./kustomize-build
